
export const readingText = `🐾 דני אוהב חיות – במיוחד את הכלב ג'וני, שמאמין שבני אדם נוצרו כדי לזרוק לו כדורים ולפנק אותו עם חטיפים. כל בוקר דני וג'וני יוצאים לטיול בפארק, פוגשים כלבים אחרים (וגם ברווז שנעלב כשלא מזמינים אותו למשחק). יום אחד ג'וני רץ אחרי חתול, והחתול דווקא רץ אחרי דני! בסוף כולם הסתבכו בתוך שיח, וכל מי שעבר בפארק קיבל הופעה בחינם. מאז דני מחליט לצאת רק עם חטיפי פיוס – גם לכלבים, גם לחתולים, וגם לברווז!`;

export const translationMap: { [hebrewWord: string]: string } = {
  "דני": "Danny",
  "אוהב": "loves",
  "חיות": "animals",
  "במיוחד": "especially",
  "הכלב": "the dog",
  "ג'וני": "Johnny",
  "מאמין": "believes",
  "בני": "people",
  "אדם": "man/human",
  "נוצרו": "were created",
  "לזרוק": "to throw",
  "כדורים": "balls",
  "לפנק": "to pamper",
  "חטיפים": "treats",
  "בוקר": "morning",
  "יוצאים": "go out",
  "טיול": "walk",
  "פארק": "park",
  "פוגשים": "meet",
  "כלבים": "dogs",
  "אחרים": "others",
  "ברווז": "duck",
  "שנעלב": "was insulted",
  "משחק": "game",
  "יום": "day",
  "אחד": "one",
  "רץ": "ran",
  "אחרי": "after",
  "חתול": "cat",
  "דווקא": "on the contrary",
  "בסוף": "in the end",
  "כולם": "everyone",
  "הסתבכו": "got entangled",
  "שיח": "bush",
  "עבר": "passed by",
  "קיבל": "got/received",
  "הופעה": "show/performance",
  "בחינם": "for free",
  "מאז": "since then",
  "מחליט": "decides",
  "חטיפי": "treats (plural base)",
  "פיוס": "reconciliation",
  "גם": "also",
  "לכלבים": "for dogs",
  "לחתולים": "for cats",
  "לברווז": "for the duck"
};
