export type PastTenseQuestion = {
  number: number;
  sentence: string;
  options: string[];
  answer: string;
  translation: string;
};

// 60 unique past-tense questions. Distractors are other past-tense persons
// of the same root, training subject-verb agreement in past tense.
export const pastTenseQuestions: PastTenseQuestion[] = [
  { number: 1, sentence: "אני ___ פיצה בערב.", options: ["אכלתי", "אכלת", "אכל", "אכלנו"], answer: "אכלתי", translation: "I ate pizza in the evening." },
  { number: 2, sentence: "אתה ___ מים אחרי הריצה.", options: ["שתית", "שתיתי", "שתה", "שתינו"], answer: "שתית", translation: "You (m.s.) drank water after the run." },
  { number: 3, sentence: "היא ___ לבית הספר ברגל.", options: ["הלכה", "הלך", "הלכו", "הלכתי"], answer: "הלכה", translation: "She walked to school." },
  { number: 4, sentence: "אנחנו ___ לסרט אתמול.", options: ["הלכנו", "הלכתי", "הלך", "הלכו"], answer: "הלכנו", translation: "We went to a movie yesterday." },
  { number: 5, sentence: "הם ___ סרט מעניין.", options: ["ראו", "ראה", "ראתה", "ראינו"], answer: "ראו", translation: "They watched an interesting movie." },
  { number: 6, sentence: "אתן ___ הרצאה ארוכה.", options: ["שמעתן", "שמעתם", "שמעו", "שמעה"], answer: "שמעתן", translation: "You (f.pl.) heard a long lecture." },
  { number: 7, sentence: "הוא ___ עם המורה.", options: ["דיבר", "דיברה", "דיברו", "דיברתי"], answer: "דיבר", translation: "He spoke with the teacher." },
  { number: 8, sentence: "אני ___ להם את האמת.", options: ["אמרתי", "אמרת", "אמר", "אמרנו"], answer: "אמרתי", translation: "I told them the truth." },
  { number: 9, sentence: "היא ___ עשר שעות אתמול בלילה.", options: ["ישנה", "ישן", "ישנו", "ישנתי"], answer: "ישנה", translation: "She slept ten hours last night." },
  { number: 10, sentence: "הם ___ בחמש בבוקר.", options: ["קמו", "קם", "קמה", "קמנו"], answer: "קמו", translation: "They got up at five in the morning." },
  { number: 11, sentence: "הילד ___ את הספר.", options: ["קרא", "קראה", "קראו", "קראת"], answer: "קרא", translation: "The boy read the book." },
  { number: 12, sentence: "המורה (אישה) ___ עברית בכיתה.", options: ["לימדה", "לימד", "לימדו", "לימדתי"], answer: "לימדה", translation: "The teacher (f.) taught Hebrew in class." },
  { number: 13, sentence: "אנחנו ___ עוגה לשבת.", options: ["אפינו", "אפיתי", "אפה", "אפו"], answer: "אפינו", translation: "We baked a cake for Shabbat." },
  { number: 14, sentence: "אתה ___ מכתב לסבא?", options: ["כתבת", "כתבתי", "כתב", "כתבנו"], answer: "כתבת", translation: "Did you (m.s.) write a letter to grandpa?" },
  { number: 15, sentence: "הסטודנטיות ___ למבחן כל הלילה.", options: ["למדו", "למד", "למדה", "למדנו"], answer: "למדו", translation: "The students (f.) studied for the exam all night." },
  { number: 16, sentence: "אתם ___ במסעדה חדשה.", options: ["אכלתם", "אכלתן", "אכל", "אכלו"], answer: "אכלתם", translation: "You (m.pl.) ate at a new restaurant." },
  { number: 17, sentence: "אני (נקבה) ___ שמלה חדשה.", options: ["קניתי", "קנית", "קנתה", "קנינו"], answer: "קניתי", translation: "I (f.) bought a new dress." },
  { number: 18, sentence: "הילדה ___ ציור יפה.", options: ["ציירה", "צייר", "ציירו", "ציירתי"], answer: "ציירה", translation: "The girl drew a beautiful picture." },
  { number: 19, sentence: "החברים שלי ___ אצלי בשבת.", options: ["היו", "היה", "הייתה", "היינו"], answer: "היו", translation: "My friends were at my place on Shabbat." },
  { number: 20, sentence: "אנחנו ___ ברכבת לתל אביב.", options: ["נסענו", "נסעתי", "נסע", "נסעו"], answer: "נסענו", translation: "We rode the train to Tel Aviv." },
  { number: 21, sentence: "הוא ___ את המפתחות בבית.", options: ["שכח", "שכחה", "שכחו", "שכחתי"], answer: "שכח", translation: "He forgot the keys at home." },
  { number: 22, sentence: "היא ___ אותי במסיבה.", options: ["פגשה", "פגש", "פגשו", "פגשתי"], answer: "פגשה", translation: "She met me at the party." },
  { number: 23, sentence: "אני (זכר) ___ לחנות בבוקר.", options: ["הלכתי", "הלכת", "הלך", "הלכנו"], answer: "הלכתי", translation: "I (m.) went to the store in the morning." },
  { number: 24, sentence: "הילדים ___ בפארק שעתיים.", options: ["שיחקו", "שיחק", "שיחקה", "שיחקנו"], answer: "שיחקו", translation: "The children played at the park for two hours." },
  { number: 25, sentence: "אתן ___ מתנה יפה.", options: ["קיבלתן", "קיבלתם", "קיבלו", "קיבלה"], answer: "קיבלתן", translation: "You (f.pl.) received a nice gift." },
  { number: 26, sentence: "אבא ___ את הדלת.", options: ["סגר", "סגרה", "סגרו", "סגרתי"], answer: "סגר", translation: "Dad closed the door." },
  { number: 27, sentence: "אמא ___ ארוחת ערב טעימה.", options: ["בישלה", "בישל", "בישלו", "בישלתי"], answer: "בישלה", translation: "Mom cooked a tasty dinner." },
  { number: 28, sentence: "הם ___ את כל המבחן בשעה.", options: ["סיימו", "סיים", "סיימה", "סיימנו"], answer: "סיימו", translation: "They finished the whole exam in an hour." },
  { number: 29, sentence: "אנחנו ___ סרט בקולנוע.", options: ["ראינו", "ראיתי", "ראה", "ראו"], answer: "ראינו", translation: "We saw a movie at the cinema." },
  { number: 30, sentence: "אני (נקבה) ___ את החדר אתמול.", options: ["ניקיתי", "ניקית", "ניקתה", "ניקינו"], answer: "ניקיתי", translation: "I (f.) cleaned the room yesterday." },
  { number: 31, sentence: "הסטודנט ___ שאלה חכמה.", options: ["שאל", "שאלה", "שאלו", "שאלתי"], answer: "שאל", translation: "The student asked a clever question." },
  { number: 32, sentence: "החברה שלי ___ אותי לארוחת צהריים.", options: ["הזמינה", "הזמין", "הזמינו", "הזמנתי"], answer: "הזמינה", translation: "My friend (f.) invited me to lunch." },
  { number: 33, sentence: "אתה ___ את החדר?", options: ["סידרת", "סידרתי", "סידר", "סידרנו"], answer: "סידרת", translation: "Did you (m.s.) tidy the room?" },
  { number: 34, sentence: "הילדה ___ בקול רם.", options: ["צחקה", "צחק", "צחקו", "צחקתי"], answer: "צחקה", translation: "The girl laughed loudly." },
  { number: 35, sentence: "אנחנו ___ ספרים בחנות.", options: ["מצאנו", "מצאתי", "מצא", "מצאו"], answer: "מצאנו", translation: "We found books in the store." },
  { number: 36, sentence: "הם ___ הביתה מאוחר.", options: ["חזרו", "חזר", "חזרה", "חזרנו"], answer: "חזרו", translation: "They returned home late." },
  { number: 37, sentence: "אני ___ את התשובה הנכונה.", options: ["ידעתי", "ידעת", "ידע", "ידעה"], answer: "ידעתי", translation: "I knew the correct answer." },
  { number: 38, sentence: "היא ___ לי הודעה.", options: ["שלחה", "שלח", "שלחו", "שלחתי"], answer: "שלחה", translation: "She sent me a message." },
  { number: 39, sentence: "אנחנו ___ במים הקרים.", options: ["שחינו", "שחיתי", "שחה", "שחו"], answer: "שחינו", translation: "We swam in the cold water." },
  { number: 40, sentence: "הוא ___ אופניים בפארק.", options: ["רכב", "רכבה", "רכבו", "רכבתי"], answer: "רכב", translation: "He rode a bike in the park." },
  { number: 41, sentence: "התלמידים ___ את שיעורי הבית.", options: ["הכינו", "הכין", "הכינה", "הכנתי"], answer: "הכינו", translation: "The students prepared the homework." },
  { number: 42, sentence: "אתן ___ במופע אתמול?", options: ["הייתן", "הייתם", "היה", "הייתי"], answer: "הייתן", translation: "Were you (f.pl.) at the show yesterday?" },
  { number: 43, sentence: "אבא ___ את המכונית בבוקר.", options: ["שטף", "שטפה", "שטפו", "שטפתי"], answer: "שטף", translation: "Dad washed the car in the morning." },
  { number: 44, sentence: "אני (זכר) ___ הרבה בחודש שעבר.", options: ["עבדתי", "עבדת", "עבד", "עבדנו"], answer: "עבדתי", translation: "I (m.) worked a lot last month." },
  { number: 45, sentence: "הילדים ___ במשחק.", options: ["ניצחו", "ניצח", "ניצחה", "ניצחנו"], answer: "ניצחו", translation: "The children won the game." },
  { number: 46, sentence: "היא ___ עוגה לכבוד יום ההולדת.", options: ["הכינה", "הכין", "הכינו", "הכנתי"], answer: "הכינה", translation: "She made a cake for the birthday." },
  { number: 47, sentence: "אנחנו ___ למסיבה בשמחה.", options: ["באנו", "באתי", "בא", "באו"], answer: "באנו", translation: "We came to the party happily." },
  { number: 48, sentence: "הם ___ בעבודה עד מאוחר.", options: ["נשארו", "נשאר", "נשארה", "נשארנו"], answer: "נשארו", translation: "They stayed at work until late." },
  { number: 49, sentence: "אתה ___ את התרגיל?", options: ["הבנת", "הבנתי", "הבין", "הבנו"], answer: "הבנת", translation: "Did you (m.s.) understand the exercise?" },
  { number: 50, sentence: "אמא ___ בגדים חדשים לילדים.", options: ["קנתה", "קנה", "קנו", "קניתי"], answer: "קנתה", translation: "Mom bought new clothes for the kids." },
  { number: 51, sentence: "אני (נקבה) ___ למוזיקה כל הערב.", options: ["הקשבתי", "הקשבת", "הקשיבה", "הקשבנו"], answer: "הקשבתי", translation: "I (f.) listened to music all evening." },
  { number: 52, sentence: "החתול ___ על העץ.", options: ["טיפס", "טיפסה", "טיפסו", "טיפסתי"], answer: "טיפס", translation: "The cat climbed the tree." },
  { number: 53, sentence: "אנחנו ___ לטיול בצפון.", options: ["יצאנו", "יצאתי", "יצא", "יצאו"], answer: "יצאנו", translation: "We set out on a trip up north." },
  { number: 54, sentence: "הילדה ___ את הספר במהירות.", options: ["סיימה", "סיים", "סיימו", "סיימתי"], answer: "סיימה", translation: "The girl finished the book quickly." },
  { number: 55, sentence: "הם ___ דירה חדשה.", options: ["מצאו", "מצא", "מצאה", "מצאנו"], answer: "מצאו", translation: "They found a new apartment." },
  { number: 56, sentence: "אני ___ עוגיות בעצמי.", options: ["אפיתי", "אפית", "אפה", "אפינו"], answer: "אפיתי", translation: "I baked cookies by myself." },
  { number: 57, sentence: "הוא ___ פרחים לחברה שלו.", options: ["נתן", "נתנה", "נתנו", "נתתי"], answer: "נתן", translation: "He gave flowers to his girlfriend." },
  { number: 58, sentence: "אתן ___ עוגה גדולה ביחד.", options: ["אפיתן", "אפיתם", "אפו", "אפה"], answer: "אפיתן", translation: "You (f.pl.) baked a big cake together." },
  { number: 59, sentence: "אנחנו ___ את הטלוויזיה בעשר.", options: ["כיבינו", "כיביתי", "כיבה", "כיבו"], answer: "כיבינו", translation: "We turned off the TV at ten." },
  { number: 60, sentence: "היא ___ את המתנה ופתחה אותה.", options: ["קיבלה", "קיבל", "קיבלו", "קיבלתי"], answer: "קיבלה", translation: "She received the gift and opened it." },
];
