// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxbpuadhwuiypkqvhduw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4YnB1YWRod3VpeXBrcXZoZHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY2OTUsImV4cCI6MjA2NTU4MjY5NX0.uP9d_EMNZcpYOSccMnLWhA0q03zOHbFr4lFByCu0G0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);